### PR TITLE
Add WKWebView compatibility

### PR DESCRIPTION
**Pull request by andreamaioli**

### CODE REVIEW

**Comment by gregavola** [comment]
@don Can this be merged in? We'd like it for WKWebView support.

**Comment by rubenstolk** [comment]
Please merge!

**Comment by isamu-tanaka** [comment]
Please merge!!  A runtime error on iOS11 always occurs.

**Comment by bucklander** [comment]
@andreamaioli thank you for this! @don This would be VERY helpful for my project as well. Could you please review and merge? 🙏

**Comment by jamesanglin** [comment]
@andreamaioli thanks for this! I would love to get this merged as well.

**Comment by jamesanglin** [comment]
@don , thanks for getting this merged in! Ionic wraps this plugin and others([(https://github.com/ionic-team/ionic-native]), but its still pointing to the 0.7.1 version. Something to do with the "npm link". Do you know how to get this updated to point to 0.7.2? Does that have to be done on this repo our theirs? Also see [https://github.com/ionic-team/ionic-native/issues/2193#issuecomment-385460140].

**Comment by don** [comment]
I think this might be a npm problem. 0.7.2 is in the repo, but the web still says 0.7.1 https://www.npmjs.com/package/phonegap-nfc. npm support suggested I push a new version.

**Comment by don** [comment]
I pushed 0.7.3 but I'm still seeing old info on the npm website. I've reopened my ticket with npm support. I'm not sure how Ionic picks the correct version.

Can you manually update the plugin in your project?

    cordova plugin rm phonegap-nfc 
    cordova plugin add phonegap-nfc@0.7.2

**Comment by jamesanglin** [comment]
@don  , Thank you so much for your help. I tried updating the plugin that way to no avail. I assume you already took these steps to publish the latest version to the npm registry? https://docs.npmjs.com/getting-started/publishing-npm-packages

If so, I read that the npmjs registry doesn't always update immediately.

**Comment by don** [comment]
@jamesanglin it turns out I was publishing to a private repo. It's fixed and code is pushed to npmjs.com now.

**Pull request merged**
