### PR TITLE
Added support for Windows/Windows Phone 8.1

### PR DESCRIPTION
**Pull request by jlkalberer**
I basically ported the code you had for WP8 to WinJS.

I didn't update the readme because you might want to format it some way.

I tested writing tags and using P2P with Android beam.

Anyways, thanks for this library and the Arduino NDEF library you wrote.  I ported that one to work with my Spark Core :)

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Wow nice thanks @jlkalberer

**Comment by don** [comment]
@jlkalberer this looks great. I won't be able to merge this until I'm back home later next week.

What NFC hardware did you use when running on Windows 8.1?

I'd be interested to see what you built with the spark core and NFC!

**Comment by jlkalberer** [comment]
I was using the Lumia 928 so I could only really test a phone.  Since Windows is running WinJs as well I am hoping that it will work there too.

The project I am working on is [this](http://johnkalberer.com/2013/07/11/tappt-beer-no-beer/).  The arduino didn't have enough memory since I had wifi and the NFC shield hooked up.  The spark core has more than enough.  I had to rebuild the circuits for the spark core but I should have my kegerator hooked up after 2-3 days of work.

Before I wrote the app in java for Android but I am using Ionic this time around and everything is going much faster and easier.

**Comment by don** [comment]
I'm still trying to track down a newer Windows Phone 8.1 device with NFC, but I have a question... The current C# WP plugin code didn't work on your Lumia 928?

**Comment by jlkalberer** [comment]
I didn't try the C# version.  That is for WP8.  I am assuming that the app will work on my phone but ionic wasn't working well with WP8 so went with WP8.1.  You can write C# in WP8.1 but that isn't what cordova uses.

When you run `cordova platform add windows` it adds a WinJS solution which has 3 projects.  Windows 8, Windows 8.1, and Windows Phone 8.1.

**Pull request merged**
