### PR TITLE
Add Tag Unique ID to iOS

### PR DESCRIPTION
**Pull request by scottire**
Adds ID object to callback.

Note: assumes the session is invalidated after a successful scan (which it currently is).

### CODE REVIEW

**Comment by don** [comment]
@scottire I'm concerned this might cause apps to be rejected because it's undocumented. Have you seen any Apple documentation talking about tag ids?

**Comment by andreamaioli** [comment]
Yesterday Apple rejected our app because we tried to use the "_foundtags" feature.

**Comment by don** [comment]
@andreamaioli thanks for the update, I was afraid of that.

**Comment by don** [comment]
Closing old pull request. Can't merge because of Apple's rules.

**Comment by Pimpf99** [comment]
Does anyone know when this feature will be allowed to use in the app store?

**Pull request closed without merging**
